print("Задача 1:")
print("Здравствуй, мир!")
print()
print("Задача 2:")
print("4", "8", "15", "16", "23", "42")
print()
print("Задача 3:")
print("4")
print("8")
print("15")
print("16")
print("23")
print("42")
print()
print("Задача 4:")
print("*")
print("**")
print("***")
print("****")
print("*****")
print("******")
print("*******")
print("Задача 5:")
print("Привет,", input())
print("Задача 6:")
print(input(), "- чемпион!")
print("Задача 7:")
print(input())
print(input())
print(input())
print("Задача 8:")
first = input()
second = input()
third = input()
print(third)
print(second)
print(first)

